table dim_customer
	lineageTag: aed5f287-02e5-44ae-83f8-8176d17f2970

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 206cc21f-e149-4de9-a3cf-225b31f0fecd
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 8065b27b-e3dd-4cbf-bbb3-ffdbfda03684
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: d512fabe-da03-4adc-8fca-813f64a01a99
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: e2fe76a2-d906-44f9-b0a9-0e2dff238cdd
		summarizeBy: none
		sourceColumn: account_manager

		annotation SummarizationSetBy = Automatic

	column payment_terms
		dataType: string
		lineageTag: 8ed82249-baaf-4a1e-91d6-2a0a5b9aae70
		summarizeBy: none
		sourceColumn: payment_terms

		annotation SummarizationSetBy = Automatic

	column concat_name
		dataType: string
		lineageTag: 485c4b3b-ff9f-421a-93de-ea8b90cd9d65
		summarizeBy: none
		sourceColumn: concat_name

		annotation SummarizationSetBy = Automatic

	column concat_email
		dataType: string
		lineageTag: 23242bad-1613-4374-8354-b29630d4bc56
		summarizeBy: none
		sourceColumn: concat_email

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: int64
		formatString: 0
		lineageTag: 3e06562a-d41d-49f9-9087-c799f3d81dfd
		summarizeBy: sum
		sourceColumn: credit_limit

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 9b02e28a-17e1-409b-834a-86160d85e8f7
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column street
		dataType: string
		lineageTag: bade830e-cab3-445d-a0a9-64ce7fc63584
		summarizeBy: none
		sourceColumn: street

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 7d8a1a19-f5e3-45e8-b624-cdf9273d00d9
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: fb4dfa43-95bf-4c39-a8e3-cc5b7d2881e7
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		queryGroup: 02_Dimensions
		source =
				let
				    Źródło = CUST_MASTER,
				    #"Przefiltrowano wiersze" = Table.SelectRows(Źródło, each ([CustomerID] <> 9999)),
				    #"Scalone zapytania" = Table.NestedJoin(#"Przefiltrowano wiersze", {"CustomerID"}, customer_contacts, {"CustomerID"}, "customer_contacts", JoinKind.LeftOuter),
				    #"Rozwinięty element customer_contacts" = Table.ExpandTableColumn(#"Scalone zapytania", "customer_contacts", {"ContactName", "Email", "IsPrimary"}, {"customer_contacts.ContactName", "customer_contacts.Email", "customer_contacts.IsPrimary"}),
				    #"Scalone zapytania1" = Table.NestedJoin(#"Rozwinięty element customer_contacts", {"CustomerID"}, user_details, {"UserID"}, "user_details", JoinKind.LeftOuter),
				    #"Rozwinięty element user_details" = Table.ExpandTableColumn(#"Scalone zapytania1", "user_details", {"CreditLimit", "Phone"}, {"user_details.CreditLimit", "user_details.Phone"}),
				    #"Scalone zapytania2" = Table.NestedJoin(#"Rozwinięty element user_details", {"AddressID"}, Address, {"AddressID"}, "Address", JoinKind.LeftOuter),
				    #"Rozwinięty element Address" = Table.ExpandTableColumn(#"Scalone zapytania2", "Address", {"Street", "CityName"}, {"Address.Street", "Address.CityName"}),
				    #"Scalone zapytania3" = Table.NestedJoin(#"Rozwinięty element Address", {"Address.CityName"}, cities, {"CityName"}, "cities", JoinKind.LeftOuter),
				    #"Rozwinięty element cities" = Table.ExpandTableColumn(#"Scalone zapytania3", "cities", {"RegionName"}, {"cities.RegionName"}),
				    #"Usunięto kolumny" = Table.RemoveColumns(#"Rozwinięty element cities",{"AddressID", "hash_key", "source_id", "customer_contacts.IsPrimary"}),
				    #"Zmieniono nazwy kolumn" = Table.RenameColumns(#"Usunięto kolumny",{{"CustomerID", "customer_id"}, {"CustomerName", "customer_name"}, {"Segment", "segment"}, {"AccountManager", "account_manager"}, {"PaymentTerms", "payment_terms"}, {"user_details.Phone", "phone"}, {"user_details.CreditLimit", "credit_limit"}, {"customer_contacts.Email", "concat_email"}, {"customer_contacts.ContactName", "concat_name"}, {"Address.Street", "street"}, {"Address.CityName", "city"}, {"cities.RegionName", "region"}})
				in
				    #"Zmieniono nazwy kolumn"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

