table fact_sales_targets
	lineageTag: 1f394a69-432f-4367-b421-ae19182dd93e

	column date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 344b9e0d-2b1e-4958-8983-fa867320e647
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column target_revenue
		dataType: int64
		formatString: 0
		lineageTag: 2d131e12-5e9d-47a5-9a47-1772281c1f94
		summarizeBy: sum
		sourceColumn: target_revenue

		annotation SummarizationSetBy = Automatic

	partition fact_sales_targets = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Źródło = sales_targets,
				    #"Zmieniono nazwy kolumn" = Table.RenameColumns(Źródło,{{"Period", "date"}, {"TargetRevenue", "target_revenue"}})
				in
				    #"Zmieniono nazwy kolumn"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

