table security
	lineageTag: 3ede88e6-a54d-41fb-a2e5-66d0fbe2440d

	column user_name
		dataType: string
		lineageTag: b7ed8846-3b93-4b81-a3cb-be09cf492484
		summarizeBy: none
		sourceColumn: user_name

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 4a0c48e5-ccf1-4d8e-aaf9-936682d82865
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition security = m
		mode: import
		queryGroup: 04_Support
		source =
				let
				    Źródło = Excel.Workbook(File.Contents("C:\Users\Justi\Desktop\powerbi\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				    security_Sheet = Źródło{[Item="security",Kind="Sheet"]}[Data],
				    #"Zmieniono typ" = Table.TransformColumnTypes(security_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Nagłówki o podwyższonym poziomie" = Table.PromoteHeaders(#"Zmieniono typ", [PromoteAllScalars=true]),
				    #"Zmieniono typ1" = Table.TransformColumnTypes(#"Nagłówki o podwyższonym poziomie",{{"UserEmail", type text}, {"Region", type text}}),
				    #"Zmieniono nazwy kolumn" = Table.RenameColumns(#"Zmieniono typ1",{{"UserEmail", "user_name"}, {"Region", "region"}})
				in
				    #"Zmieniono nazwy kolumn"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Nawigacja

