table dim_geo
	lineageTag: a2a5115a-8b62-420c-83c5-6c5e97253040

	column geo_key
		dataType: int64
		formatString: 0
		lineageTag: 1a4f8f64-e925-4189-97a9-5932f6eb0a26
		summarizeBy: none
		sourceColumn: geo_key

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: f97dff68-4dc2-472e-b948-ea9ecd447c2b
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 2be24c86-fdfe-4a31-bd32-0badd04f56db
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_geo = m
		mode: import
		queryGroup: 02_Dimensions
		source =
				let
				    Źródło = cities,
				    #"Usunięto duplikaty" = Table.Distinct(Źródło),
				    #"Dodano indeks" = Table.AddIndexColumn(#"Usunięto duplikaty", "Indeks", 1, 1, Int64.Type),
				    #"Zmieniono nazwy kolumn" = Table.RenameColumns(#"Dodano indeks",{{"Indeks", "geo_key"}}),
				    #"Zmieniono kolejność kolumn" = Table.ReorderColumns(#"Zmieniono nazwy kolumn",{"geo_key", "CityName", "RegionName"}),
				    #"Zmieniono nazwy kolumn1" = Table.RenameColumns(#"Zmieniono kolejność kolumn",{{"CityName", "city"}, {"RegionName", "region"}})
				in
				    #"Zmieniono nazwy kolumn1"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

