table fact_order_process
	lineageTag: 07fc0dde-c996-4476-85ba-965351ccbaf1

	column order_id
		dataType: string
		lineageTag: 9399ebc1-2c7a-4229-b420-d60546a6500a
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: efe6b14a-ec79-425a-ac3f-39da7441a6df
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: e9403ec0-b918-4b0e-98e8-f0acec8aca71
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ship_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 40b26d29-a2db-4a3d-80e5-5e782ca7acfd
		summarizeBy: none
		sourceColumn: ship_date

		variation Odmiana
			isDefault
			relationship: 9927e7ed-d662-4cc5-85af-7843f46bf609
			defaultHierarchy: LocalDateTable_515a3c93-93de-4d5e-bfe1-34dda0c10bbf.'Hierarchia dat'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column delivery_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: c95e8c8e-9bd9-42ae-bd24-f3787bb0818b
		summarizeBy: none
		sourceColumn: delivery_date

		variation Odmiana
			isDefault
			relationship: db763608-5ea5-47d5-b80d-b1ce8249b9ba
			defaultHierarchy: LocalDateTable_7885b97a-4882-43b0-9825-504e72dffb6f.'Hierarchia dat'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column invoice_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: f261dd48-00a4-417d-bab2-91fc04e76ed5
		summarizeBy: none
		sourceColumn: invoice_date

		variation Odmiana
			isDefault
			relationship: 44c63685-6cab-4e5a-84e5-c3c412874073
			defaultHierarchy: LocalDateTable_57cdbbdb-36b6-46f7-a845-d676850b84d5.'Hierarchia dat'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column pay_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: a02a1727-6932-4dfc-8b98-0bc4282d8643
		summarizeBy: none
		sourceColumn: pay_date

		variation Odmiana
			isDefault
			relationship: d0b4f916-1f22-4d3a-a004-8fbb2f92afea
			defaultHierarchy: LocalDateTable_05780544-4bf8-472f-9759-c07d38dc4bf7.'Hierarchia dat'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column order_to_pay = DATEDIFF(fact_order_process[order_date], fact_order_process[pay_date], DAY)
		formatString: 0
		lineageTag: 65cc3ddd-f497-4b1d-bdc6-242b541ecf3a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fact_order_process = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Źródło = orders,
				    #"Usunięto kolumny" = Table.RemoveColumns(Źródło,{"CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Scalone zapytania" = Table.NestedJoin(#"Usunięto kolumny", {"CustomerName"}, dim_customer, {"customer_name"}, "dim_customer", JoinKind.LeftOuter),
				    #"Rozwinięty element dim_customer" = Table.ExpandTableColumn(#"Scalone zapytania", "dim_customer", {"customer_id"}, {"dim_customer.customer_id"}),
				    #"Zmieniono kolejność kolumn" = Table.ReorderColumns(#"Rozwinięty element dim_customer",{"OrderID", "dim_customer.customer_id", "CustomerName", "OrderDate"}),
				    #"Usunięto kolumny1" = Table.RemoveColumns(#"Zmieniono kolejność kolumn",{"CustomerName"}),
				    #"Scalone zapytania1" = Table.NestedJoin(#"Usunięto kolumny1", {"OrderID"}, shipments, {"OrderID"}, "shipments", JoinKind.LeftOuter),
				    #"Rozwinięty element shipments" = Table.ExpandTableColumn(#"Scalone zapytania1", "shipments", {"ShipDate", "DeliveryDate"}, {"shipments.ShipDate", "shipments.DeliveryDate"}),
				    #"Scalone zapytania2" = Table.NestedJoin(#"Rozwinięty element shipments", {"OrderID"}, INVOICES, {"OrderID"}, "INVOICES", JoinKind.LeftOuter),
				    #"Rozwinięty element INVOICES1" = Table.ExpandTableColumn(#"Scalone zapytania2", "INVOICES", {"InvoiceID", "InvoiceDate"}, {"INVOICES.InvoiceID", "INVOICES.InvoiceDate"}),
				    #"Scalone zapytania3" = Table.NestedJoin(#"Rozwinięty element INVOICES1", {"INVOICES.InvoiceID"}, payments, {"InvoiceID"}, "payments", JoinKind.LeftOuter),
				    #"Rozwinięty element payments" = Table.ExpandTableColumn(#"Scalone zapytania3", "payments", {"PayDate"}, {"payments.PayDate"}),
				    #"Usunięto kolumny2" = Table.RemoveColumns(#"Rozwinięty element payments",{"INVOICES.InvoiceID"}),
				    #"Zmieniono nazwy kolumn" = Table.RenameColumns(#"Usunięto kolumny2",{{"OrderID", "order_id"}, {"dim_customer.customer_id", "customer_id"}, {"OrderDate", "order_date"}, {"shipments.ShipDate", "ship_date"}, {"shipments.DeliveryDate", "delivery_date"}, {"INVOICES.InvoiceDate", "invoice_date"}, {"payments.PayDate", "pay_date"}}),
				    #"Zmieniono typ" = Table.TransformColumnTypes(#"Zmieniono nazwy kolumn",{{"order_date", type date}})
				in
				    #"Zmieniono typ"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

