table fact_sales
	lineageTag: a3d3c944-e687-45ba-9e47-e7b50a5b9b26

	column line_id
		dataType: string
		lineageTag: 60ae4589-645d-4640-9a49-41f8a21991a1
		summarizeBy: none
		sourceColumn: line_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 41312d67-fc02-424a-95bd-327f85ab75e6
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 2d920ded-a607-43b0-90a1-be3b74efbac0
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: 9d4f1771-c1d7-4e45-979d-fc00d366565d
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cost
		dataType: double
		lineageTag: 7fa4b406-6cdb-4739-9254-9e2c67da0f98
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discount
		dataType: double
		lineageTag: 1cc53845-6266-4033-9ed9-844abd283313
		summarizeBy: sum
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column line_total
		dataType: double
		formatString: 0.00
		lineageTag: dea0f6a8-1b43-4322-a5d1-9e71f2d25701
		summarizeBy: sum
		sourceColumn: line_total

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: a786ceff-e782-4c4e-82be-b481841ada05
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 0ba478f9-516d-45fa-a580-7218f8b56485
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: c4460005-fac9-4a92-9a6b-d9dd05bb4a71
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column flag_key
		dataType: int64
		formatString: 0
		lineageTag: 4e711040-aeb1-4eac-b56e-8f8a3785b6a2
		summarizeBy: none
		sourceColumn: flag_key

		annotation SummarizationSetBy = Automatic

	column ship_to_city_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 84df0552-d59c-462c-b80b-dc481ebb5944
		summarizeBy: none
		sourceColumn: ship_to_city_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column bill_to_city_key
		dataType: int64
		formatString: 0
		lineageTag: b98c087e-20d1-4fbf-a467-f15ba9722054
		summarizeBy: sum
		sourceColumn: bill_to_city_key

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Źródło = order_line_items,
				    #"Scalone zapytania" = Table.NestedJoin(Źródło, {"OrderID"}, orders, {"OrderID"}, "orders", JoinKind.LeftOuter),
				    #"Rozwinięty element orders" = Table.ExpandTableColumn(#"Scalone zapytania", "orders", {"CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}, {"orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "orders.OrderChannel", "orders.Status", "orders.Priority", "orders.OrderTotal"}),
				    #"Scalone zapytania1" = Table.NestedJoin(#"Rozwinięty element orders", {"orders.CustomerName"}, dim_customer, {"customer_name"}, "dim_customer", JoinKind.LeftOuter),
				    #"Rozwinięty element dim_customer" = Table.ExpandTableColumn(#"Scalone zapytania1", "dim_customer", {"customer_id"}, {"dim_customer.customer_id"}),
				    #"Zmieniono kolejność kolumn" = Table.ReorderColumns(#"Rozwinięty element dim_customer",{"LineID", "OrderID", "ProductName", "dim_customer.customer_id", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "orders.OrderChannel", "orders.Status", "orders.Priority", "orders.OrderTotal"}),
				    #"Scalone zapytania2" = Table.NestedJoin(#"Zmieniono kolejność kolumn", {"ProductName"}, dim_product, {"product_name"}, "dim_product", JoinKind.LeftOuter),
				    #"Rozwinięty element dim_product" = Table.ExpandTableColumn(#"Scalone zapytania2", "dim_product", {"product_key"}, {"dim_product.product_key"}),
				    #"Zmieniono kolejność kolumn1" = Table.ReorderColumns(#"Rozwinięty element dim_product",{"LineID", "OrderID", "ProductName", "dim_product.product_key", "dim_customer.customer_id", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "orders.OrderChannel", "orders.Status", "orders.Priority", "orders.OrderTotal"}),
				    #"Scalone zapytania3" = Table.NestedJoin(#"Zmieniono kolejność kolumn1", {"orders.OrderChannel", "orders.Status", "orders.Priority"}, dim_order_flags, {"channel_code", "status", "priority"}, "dim_order_flags", JoinKind.LeftOuter),
				    #"Rozwinięty element dim_order_flags" = Table.ExpandTableColumn(#"Scalone zapytania3", "dim_order_flags", {"flag_key"}, {"dim_order_flags.flag_key"}),
				    #"Zmieniono kolejność kolumn2" = Table.ReorderColumns(#"Rozwinięty element dim_order_flags",{"LineID", "OrderID", "ProductName", "dim_product.product_key", "dim_customer.customer_id", "dim_order_flags.flag_key", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "orders.OrderChannel", "orders.Status", "orders.Priority", "orders.OrderTotal"}),
				    #"Usunięto kolumny" = Table.RemoveColumns(#"Zmieniono kolejność kolumn2",{"ProductName"}),
				    #"Zmieniono nazwy kolumn" = Table.RenameColumns(#"Usunięto kolumny",{{"LineID", "line_id"}, {"OrderID", "order_id"}, {"dim_product.product_key", "product_key"}, {"dim_customer.customer_id", "customer_id"}, {"dim_order_flags.flag_key", "flag_key"}, {"Quantity", "quantity"}, {"UnitPrice", "price"}, {"DiscountPct", "discount"}, {"LineTotal", "line_total"}, {"UnitCost", "cost"}}),
				    #"Usunięto kolumny1" = Table.RemoveColumns(#"Zmieniono nazwy kolumn",{"orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.OrderChannel", "orders.Status", "orders.Priority"}),
				    #"Zmieniono kolejność kolumn3" = Table.ReorderColumns(#"Usunięto kolumny1",{"line_id", "order_id", "product_key", "customer_id", "flag_key", "quantity", "price", "cost", "discount", "line_total", "orders.OrderTotal", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate"}),
				    #"Usunięto kolumny2" = Table.RemoveColumns(#"Zmieniono kolejność kolumn3",{"orders.OrderTotal"}),
				    #"Zmieniono nazwy kolumn1" = Table.RenameColumns(#"Usunięto kolumny2",{{"orders.OrderDate", "order_date"}}),
				    #"Zmieniono kolejność kolumn4" = Table.ReorderColumns(#"Zmieniono nazwy kolumn1",{"line_id", "order_id", "product_key", "customer_id", "flag_key", "orders.ShipToCity", "orders.BillToCity", "order_date", "quantity", "price", "cost", "discount", "line_total"}),
				    #"Scalone zapytania4" = Table.NestedJoin(#"Zmieniono kolejność kolumn4", {"orders.ShipToCity"}, dim_geo, {"city"}, "dim_geo", JoinKind.LeftOuter),
				    #"Rozwinięty element dim_geo" = Table.ExpandTableColumn(#"Scalone zapytania4", "dim_geo", {"geo_key"}, {"dim_geo.geo_key"}),
				    #"Scalone zapytania5" = Table.NestedJoin(#"Rozwinięty element dim_geo", {"orders.BillToCity"}, dim_geo, {"city"}, "dim_geo", JoinKind.LeftOuter),
				    #"Rozwinięty element dim_geo1" = Table.ExpandTableColumn(#"Scalone zapytania5", "dim_geo", {"geo_key"}, {"dim_geo.geo_key.1"}),
				    #"Zmieniono nazwy kolumn2" = Table.RenameColumns(#"Rozwinięty element dim_geo1",{{"dim_geo.geo_key", "ship_to_city_key"}, {"dim_geo.geo_key.1", "bill_to_city_key"}}),
				    #"Zmieniono kolejność kolumn5" = Table.ReorderColumns(#"Zmieniono nazwy kolumn2",{"line_id", "order_id", "product_key", "customer_id", "flag_key", "ship_to_city_key", "bill_to_city_key", "orders.ShipToCity", "orders.BillToCity", "order_date", "quantity", "price", "cost", "discount", "line_total"}),
				    #"Usunięto kolumny3" = Table.RemoveColumns(#"Zmieniono kolejność kolumn5",{"orders.ShipToCity", "orders.BillToCity"}),
				    #"Zmieniono typ" = Table.TransformColumnTypes(#"Usunięto kolumny3",{{"order_date", type date}})
				in
				    #"Zmieniono typ"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

