table fact_campaign_spend
	lineageTag: f5d16092-bfe1-4864-b1e7-02f832b59db4

	column campaign_key
		dataType: int64
		formatString: 0
		lineageTag: abb6dbb2-20a3-44be-9191-60a8e3cb72c8
		summarizeBy: none
		sourceColumn: campaign_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 864ca6f5-30e4-4d67-9fb9-61c6ebe4dbb5
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column impressions
		dataType: int64
		formatString: 0
		lineageTag: ec6f668b-0023-4e9a-8097-20d536268e7d
		summarizeBy: sum
		sourceColumn: impressions

		annotation SummarizationSetBy = Automatic

	column clicks
		dataType: int64
		formatString: 0
		lineageTag: 91b00979-742f-453d-be7a-087366eb1ad3
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		lineageTag: 216dd918-4cb2-4df6-a47e-1b181bb6cb78
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_campaign_spend = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Źródło = CAMPAIGN_LOG,
				    #"Scalone zapytania" = Table.NestedJoin(Źródło, {"CampaignName"}, dim_campaign, {"campaign_name"}, "dim_campaign", JoinKind.LeftOuter),
				    #"Rozwinięty element dim_campaign" = Table.ExpandTableColumn(#"Scalone zapytania", "dim_campaign", {"campaign_key"}, {"dim_campaign.campaign_key"}),
				    #"Zmieniono kolejność kolumn" = Table.ReorderColumns(#"Rozwinięty element dim_campaign",{"dim_campaign.campaign_key", "CampaignName", "Channel", "StartDate", "EndDate", "Budget", "Date", "Impressions", "Clicks", "Spend"}),
				    #"Usunięto kolumny" = Table.RemoveColumns(#"Zmieniono kolejność kolumn",{"CampaignName", "Channel", "StartDate", "EndDate", "Budget"}),
				    #"Zmieniono nazwy kolumn" = Table.RenameColumns(#"Usunięto kolumny",{{"dim_campaign.campaign_key", "campaign_key"}, {"Date", "date"}, {"Impressions", "impressions"}, {"Clicks", "clicks"}, {"Spend", "spend"}})
				in
				    #"Zmieniono nazwy kolumn"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

